Updated test for correct behaviour on bugfix branch.

diff --git a/.github/workflows/test-current-branch.yml b/.github/workflows/test-current-branch.yml
--- a/.github/workflows/test-current-branch.yml
+++ b/.github/workflows/test-current-branch.yml
@@ -41,7 +41,7 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-maven-
 
-    - name: Run action (non-branch version)
+    - name: Run action (non-branch version - should fail)
       id: run-action-non-branch-version
       uses: maven-flow/manage-versions@main
       env:
@@ -52,14 +52,19 @@ jobs:
         maven-args: "-P github -s ${GITHUB_WORKSPACE}/.github/workflows/maven-settings.xml"
         pom-file: "non-branch-version-pom.xml"
 
-    - name: Assert version unchanged
-      run: .github/workflows/assert-project-version.sh non-branch-version-pom.xml 1.1.0-rc.0-SNAPSHOT
-
-    - name: Assert dependency version unchanged
-      run: .github/workflows/assert-dependency-version.sh non-branch-version-pom.xml com.jardoapps.maven-flow dummy-dependency 1.1.0-rc.0-SNAPSHOT
+    - name: Assert version check failed
+      if: '!cancelled()' # continue despite run-action-non-branch-version failing, which is correct
+      run: |
+        if [[ steps.run-action-non-branch-version.outputs.status == "failure" ]]; then
+            echo "Version check failed, which is correct."
+        else
+            echo "ERROR: Version check did not fail, which is incorrect."
+            exit 1
+        fi
 
     - name: Run action (branch version)
       id: run-action-branch-version
+      if: '!cancelled()' # continue despite run-action-non-branch-version failing, which is correct
       uses: maven-flow/manage-versions@main
       env:
         USER: ${{ secrets.USER }}
@@ -69,8 +74,10 @@ jobs:
         maven-args: "-P github -s ${GITHUB_WORKSPACE}/.github/workflows/maven-settings.xml"
         pom-file: "branch-version-pom.xml"
 
-    - name: Assert version changed
-      run: .github/workflows/assert-project-version.sh branch-version-pom.xml 1.1.0-rc.0-SNAPSHOT
+    - name: Assert version unchanged
+      if: '!cancelled()' # continue despite run-action-non-branch-version failing, which is correct
+      run: .github/workflows/assert-project-version.sh branch-version-pom.xml 1.1.0-rc.0-BUG-458-SNAPSHOT
 
-    - name: Assert dependency version changed
-      run: .github/workflows/assert-dependency-version.sh branch-version-pom.xml com.jardoapps.maven-flow dummy-dependency 1.1.0-rc.0-SNAPSHOT
+    - name: Assert dependency version unchanged
+      if: '!cancelled()' # continue despite run-action-non-branch-version failing, which is correct
+      run: .github/workflows/assert-dependency-version.sh branch-version-pom.xml com.jardoapps.maven-flow dummy-dependency 1.1.0-rc.0-BUG-458-SNAPSHOT
